//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyDescription("骑马与砍杀 2: 暗夜刀锋修改器")]
[assembly: System.CLSCompliant(false)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyInformationalVersion("1.5.9.1")]
[assembly: System.Reflection.AssemblyCopyright("版权所有@骑砍中文站 cnedwin")]
[assembly: System.Reflection.AssemblyFileVersion("1.5.7")]
[assembly: System.Reflection.AssemblyVersion("1.5.7")]
[assembly: System.Reflection.AssemblyTitle("MBEditor")]


