//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("MBEditor")]
[assembly: System.Reflection.AssemblyDescription("Mount & Blade 2: Bannerlord Editor")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © shadowglaze")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyVersion("1.4.1")]
[assembly: System.Reflection.AssemblyFileVersion("1.4.1")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.5.4-10")]


